name: AutoMessage
version: 1
main: me.rejomy.automessage.Main
api-version: 1.21
commands:
  automessage:
    permission: automessage.command
    permission-message: You don`t have permission for perform this command.